# Generated by Django 4.2.1 on 2024-04-24 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sondage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('lieux', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('heure', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='DateSondage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('sondage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Doodle.sondage')),
            ],
            options={
                'unique_together': {('sondage', 'date')},
            },
        ),
    ]
