# Generated by Django 5.0.6 on 2024-05-22 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doodle', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datesondage',
            name='votes',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_sondage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Doodle.datesondage')),
            ],
        ),
    ]
